import { chromium } from '@playwright/test'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1366, height: 768 } })
p.on('pageerror', e => console.log('PAGEERROR:', (e.stack || e.message).split('\n').slice(0,4).join(' | ')))
await p.goto('http://localhost:5173/trial', { waitUntil: 'load' })
await p.waitForTimeout(2000)
await p.locator('button', { hasText: '开始试玩' }).first().click()
await p.waitForTimeout(2400)
await p.locator('#sendButton').click()
await p.waitForTimeout(1000)
await p.locator('#inputMessage').fill('是啊')
await p.locator('#inputMessage').press('Enter')
await p.waitForTimeout(1500)
await b.close()
