const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const js = fs.readFileSync(path.join(root, "app.js"), "utf8");

assert.match(html, /data-hotspot-id="CH1_NOTE_01"/);
assert.match(html, /data-hotspot-id="CH1_C02_DOOR"/);
assert.match(html, /data-hotspot-id="CH1_CHARACTER_REGISTRY"/);
assert.doesNotMatch(html, /id="switch-(deepseek|claude|chatgpt|doubao)"/);
assert.match(html, /id="rubbing-surface"/);
assert.match(html, /id="rubbing-canvas"/);
assert.match(js, /INSPECT_HOTSPOT/);
assert.match(js, /const isPaperHotspot = button\.dataset\.hotspotId === "CH1_NOTE_01"/);
assert.match(js, /openInvestigationDetail\(button\.dataset\.hotspotId\)/);
assert.match(js, /PAPER_RUBBING_COMPLETE/);
assert.match(js, /GRID_COLUMNS = 28/);
assert.match(js, /GRID_ROWS = 15/);
assert.match(js, /COMPLETE_COVERAGE = 0\.38/);
assert.match(js, /destination-out/);
assert.match(js, /不要把管理员权限交给/);
assert.match(js, /—— V03/);
assert.match(js, /api\/game\/action/);
assert.match(js, /api\/game\/state/);
assert.match(html, /id="game-modal"/);
assert.match(html, /id="modal-close"/);
assert.match(html, /id="evidence-panel"/);
assert.doesNotMatch(html, /evidence-presentation-hint/);
assert.match(html, /id="investigation-panel"/);
assert.match(html, /id="investigation-confirm"/);
assert.match(html, /data-hotspot-id="CH1_TERMINAL_MAIN" hidden/);
assert.doesNotMatch(html, /class="history-panel interactive-ui"/);
assert.match(js, /api\/game\/evidence/);
assert.match(js, /api\/game\/present/);
assert.match(js, /evidence_presentation/);
assert.match(js, /presentableCharacterIds/);
assert.match(js, /openGameModal\("evidence", \{ highlightEvidenceId: data\.evidence_id \}\)/);
assert.match(js, /is-highlighted/);
assert.match(html, /推理请以 \/推理 开头/);
assert.match(html, /输入你想说的话/);
assert.match(js, /api\/game\/deduction/);
assert.match(html, /id="claude-private-interview"/);
assert.match(js, /api\/game\/private-interview\/challenge/);
assert.match(js, /loadInvestigationState\(\)\.catch/);
assert.match(js, /applyPresentation\(data\.presentation\)/);
assert.match(js, /state\.available_hotspots/);
assert.match(js, /hotspot_id: "CH1_NOTE_01"/);
assert.match(js, /hasAuthoredHotspots/);
assert.match(js, /这里暂时无法调查/);
assert.match(js, /errorBody\.detail/);
assert.match(js, /这里暂时无法调查。先检查房间里已经出现的异常。/);
assert.match(js, /无法连接调查服务/);

console.log("CH1 investigation UI wiring: PASS");
